# Generated by Django 3.1.4 on 2020-12-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='lat',
            field=models.DecimalField(decimal_places=14, default=28.51294614131052, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='lng',
            field=models.DecimalField(decimal_places=14, default=34.51415840811709, max_digits=17),
            preserve_default=False,
        ),
    ]
