# Generated by Django 3.1.4 on 2020-12-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_auto_20201215_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='country',
            field=models.CharField(max_length=200),
        ),
    ]
